---
- hosts: grpA
  become: yes
  tasks:
  - name: "installing apache"
    apt:
      name: apache2
      state: present
  - name: "ensure the Service stopped"
    service:
      name: apache2
      state: stopped

